apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-disk
        persistentVolumeClaim:
          claimName: mysql-claim
      containers:
      - name: mysql
        image: mysql:5
        args:
        - "--ignore-db-dir=lost+found"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: nestjs_demo
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-disk