apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany, ReadWriteMany, ReadWriteOncePod check docs here https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  resources:
    requests:
      storage: 10Gi
  # storageClassName: ssd